#ifndef MAGE_TCN_PARAMETERS_H
#define MAGE_TCN_PARAMETERS_H

#include "mage_cgra.h"

#define MAGE_INPUTS_START_ADDR = MAGE_BANK_0
#define MAGE_OUTPUTS_START_ADDR = MAGE_BANK_6
#define MAGE_WEIGHTS_START_ADDR = MAGE_BANK_4

#endif // MAGE_TCN_PARAMETERS_H